DEFAULT_BOOKS = [
    {
        "id": 1,
        "title": "Machine Learning Algorithm",
        "author": "CSTU Library",
        "category": "General",
        "status": "Available",
        "image": "/images/front_img_cover.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 2,
        "title": "Engineering II",
        "author": "Academic Press",
        "category": "Engineering",
        "status": "Available",
        "image": "/images/Engineering_II_Cover_WEB.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 3,
        "title": "C++ Programming",
        "author": "Brian Kernighan",
        "category": "Programming",
        "status": "Available",
        "image": "/images/c-programming.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 4,
        "title": "Fundamentals of Mathematics",
        "author": "CSTU Research Unit",
        "category": "Mathematics",
        "status": "Issued",
        "image": "/images/fundamentals-of-math.jpg",
        "issuedBy": "self",
        "copiesAvailable": 15,
    },
    {
        "id": 5,
        "title": "Bots and Automation",
        "author": "Tech Future Team",
        "category": "Robotics",
        "status": "Available",
        "image": "/images/bots-cover.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 6,
        "title": "Big Data Essentials",
        "author": "Data Lab",
        "category": "Data Science",
        "status": "Issued",
        "image": "/images/bigdata-cover.jpg",
        "issuedBy": "other",
        "copiesAvailable": 15,
    },
    {
        "id": 7,
        "title": "Operating Systems",
        "author": "Silberschatz",
        "category": "Computer Science",
        "status": "Available",
        "image": "/images/os-cover.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 8,
        "title": "Machine Learning",
        "author": "CSE Final Question",
        "category": "Computer Science",
        "status": "Available",
        "image": "/images/cover_fmt.jpg",
        "issuedBy": None,
        "copiesAvailable": 15,
    },
    {
        "id": 9,
        "title": "Robotics Fundamentals",
        "author": "STEM Library",
        "category": "Robotics",
        "status": "Issued",
        "image": "/images/robotics-cover.jpg",
        "issuedBy": "self",
        "copiesAvailable": 15,
    },
]
